title: Site Title
author: GitHub User
email: your-email@domain.com
theme: minima
description: > no description
{% comment %}
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this line in _config.yml.
  It will appear in your document head meta (for Google search results) and in your feed.xml site description.
{% endcomment %}

github_username: goacfowo # DO NOT include the @ character, or else the build will fail!
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to true/false to show/remove excerpts on the homepage

{% comment %}
<!-- Begin Jekyll SEO tag v2.7.1 -->
<title>Welcome to my blog | Your awesome title</title>
<meta name="generator" content="Jekyll v3.9.0" />
<meta property="og:title" content="Welcome to my blog" />
<meta name="author" content="GitHub User" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description." />
<meta property="og:description" content="Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description." />
<link rel="canonical" href="https://goacfowo.github.io/github-pages-with-jekyll/" />
<meta property="og:url" content="https://goacfowo.github.io/github-pages-with-jekyll/" />
<meta property="og:site_name" content="Your awesome title" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="Welcome to my blog" />
<script type="application/ld+json">
{"description":"Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.","url":"https://goacfowo.github.io/github-pages-with-jekyll/","@type":"WebSite","headline":"Welcome to my blog","name":"Your awesome title","author":{"@type":"Person","name":"GitHub User"},"@context":"https://schema.org"}</script>
<!-- End Jekyll SEO tag -->
{% endcomment %}
