title: Site Title
author: Author
email: email@domain.net
theme: minima
description: no description
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this line in _config.yml.
#   It will appear in your document head meta (for Google search results) and in your feed.xml site description.

github_username: goacfowo # DO NOT include the @ character, or else the build will fail!  
# facebook_username: goacfowo # DO NOT include the @ character, or else the build will fail!  
# twitter_username: goacfowo # DO NOT include the @ character, or else the build will fail!  
# telegram_username: goacfowo # DO NOT include the @ character, or else the build will fail! # doesn't work  

show_excerpts: true # set to true/false to show/remove excerpts on the homepage
